import type { ReactiveObject } from "../../utils";
import type { ChatContext, ThemeTokens } from "./types";


export const defaultTheme: ThemeTokens = {
    root: {
        bezier: 'cubic-bezier(.4, .4, .2, 1)',
        primary: '#0070FF',
        color: 'transparent',
        borderColor: 'transparent',
        boxShadow: 'none',
        borderRadius: '0',
        borderSize: '0',
        padding: '0',
      },
      header: {
        color: 'transparent',
        borderColor: '#0000001a',
        boxShadow: 'none',
        borderRadius: '0',
        borderSize: '0 0 1px 0',
        padding: '5px',
        titleFontSize: '16px',
        titleFontWeight: '600',
        fontSize: '14px',
        fontWeight: '400',
        titleTextColor: '#333639',
        backColor: '#333639',
        backColorHover: '#004dfb',
        backColorPressed: '#004dfb',
        subtitleTextColor: '#d4d4d4',
        backSize: '22px',
      },
      body: {
        color: 'transparent',
        backdropFilter: '',
        width: '100%',
        maxWidth: '800px',
        padding: '5px',
        margin: '0 auto',
        toBottomColor: '#ffffff',
        toBottomSize: '32px',
        toBottomBorderRadius: '16px',
        toBottomColorHover: '#F6F7F9',
        toBottomTextColor: '#1a1a1a',
        toBottomTextColorHover: '#1a1a1a',
        toBottomBorderColor: '#0000001a',
        toBottomBorderColorHover: '#0000001a',
      },
      bubble: {
        sendColor: '#0070ff',
        sendTextColor: '#ffffff',
        respondColor: '#f8f8f8',
        respondTextColor: '',
        avatarSize: '34px',
        avatarPadding: '0',
        avatarMargin: '0',
        avatarBorderColor: 'transparent',
        avatarBorderSize: '0',
        avatarBoxShadow: 'none',
        avatarBorderRadius: '0',
        borderColor: 'transparent',
        borderSize: '0',
        boxShadow: 'none',
        borderRadius: '8px',
        padding: '10px',
        margin: '0',
        backdropFilter: '',
      },
      footer: {
        color: 'transparent',
        fontSize: '12px',
        textColor: 'rgba(0, 0, 0, 0.2)',
        padding: '5px 16px 5px 16px',
      },
      input: {
        color: '#ffffff',
        backdropFilter: '',
        colorDisabled: '#f3f4f6',
        colorFocus: '#ffffff',
        textColor: '',
        textColorDisabled: '',
        textColorFocus: '',
        inputFontSize: '14',
        inputFontWeight: '400',
        inputPadding: '5px',
        inputBorderRadius: '20px',
        inputColor: '',
        inputColorDisabled: '',
        inputTextColor: '',
        inputTextColorDisabled: '',
        inputTextColorFocus: '',
        placeholderColor: '#00000050',
        placeholderColorDisabled: '#00000030',
        width: '100%',
        height: 'auto',
        maxWidth: '800px',
        maxHeight: '235px',
        fontSize: '16px',
        lineHeight: '30px',
        border: '1px solid #ccc',
        borderHover: '1px solid #ccc',
        borderDisabled: '1px solid #ccc',
        borderFocus: '1px solid #ccc',
        borderRadius: '20px',
        boxShadow: '',
        boxShadowFocus: '',
        boxShadowDisabled: '',
        padding: '5px',
        margin: '0 auto',
    },
}

export const chatContexts = new WeakMap<
  HTMLElement,
  ReactiveObject<ChatContext>
>();
